CORES_ATIVADAS=true
EXCLUSOES_PADRAO="node_modules .git dist build"
DESCRICOES_ATIVADAS=true
ICONES_ATIVADOS=true
ABRIR_NAVEGADOR_AUTO=true
CONFIRMAR_EXECUCAO=true
MOSTRAR_LOG_FALHA=true
DIAGNOSTICO_NA_ABERTURA=false
LIMPAR_TEMPORARIOS_AUTO=true
TEMPO_DETECTAR_PORTA=15
PAUSA_ERRO_SEGUNDOS=1
LOG_MAX_MB=5
DESTINO_IMPORTACAO_PADRAO="perguntar"
CONFLITO_PADRAO="perguntar"
CONFIRMAR_COPIA=true
