import mongoose from 'mongoose'

const platformStateSchema = new mongoose.Schema({
  id: { type:String, default:'' },
  status: { type:String, default:'pending' },
  url: { type:String, default:'' },
  message: { type:String, default:'' },
  checkedAt: { type:Date, default:null },
}, { _id:false })

const updateReleaseSchema = new mongoose.Schema({
  releaseId: { type:String, required:true, unique:true, index:true },
  version: { type:String, required:true, index:true },
  fromVersion: { type:String, default:'' },
  filename: { type:String, required:true },
  packageType: { type:String, default:'full' },
  packageSha256: { type:String, required:true },
  packageBytes: { type:Number, default:0 },
  bucket: { type:String, required:true },
  objectKey: { type:String, required:true },
  storage: { type:String, default:'r2' },
  changelog: { type:String, default:'' },
  integrity: { type:mongoose.Schema.Types.Mixed, default:{} },
  status: { type:String, default:'ready', index:true },
  repository: { type:String, default:'' },
  branch: { type:String, default:'main' },
  publishMode: { type:String, default:'project' },
  commitSha: { type:String, default:'' },
  commitUrl: { type:String, default:'' },
  previousCommitSha: { type:String, default:'' },
  githubStatus: { type:String, default:'pending' },
  githubVerified: { type:Boolean, default:false },
  githubVerifiedAt: { type:Date, default:null },
  githubVerification: { type:mongoose.Schema.Types.Mixed, default:{} },
  productionTarget: { type:mongoose.Schema.Types.Mixed, default:{} },
  targetLockedAt: { type:Date, default:null },
  publishJobId: { type:String, default:'' },
  publishStatus: { type:String, default:'' },
  publishPhase: { type:String, default:'' },
  publishPhaseLabel: { type:String, default:'' },
  publishProgress: { type:Number, default:0 },
  publishHeartbeatAt: { type:Date, default:null },
  publishStartedAt: { type:Date, default:null },
  publishCompletedAt: { type:Date, default:null },
  publishAttempts: { type:Number, default:0 },
  publishError: { type:String, default:'' },
  publishCommitMessage: { type:String, default:'' },
  publishCandidateSha: { type:String, default:'' },
  publishCandidateUrl: { type:String, default:'' },
  publishCandidateAt: { type:Date, default:null },
  publishTimeline: { type:[mongoose.Schema.Types.Mixed], default:[] },
  publishFileLog: { type:[mongoose.Schema.Types.Mixed], default:[] },
  publishCurrentFile: { type:mongoose.Schema.Types.Mixed, default:{} },
  publishFilesDone: { type:Number, default:0 },
  publishFilesTotal: { type:Number, default:0 },
  trackingStartedAt: { type:Date, default:null },
  lastCheckedAt: { type:Date, default:null },
  trackingAttempts: { type:Number, default:0 },
  stalledAt: { type:Date, default:null },
  interruptedAt: { type:Date, default:null },
  recovery: { type:mongoose.Schema.Types.Mixed, default:{} },
  vercel: { type:platformStateSchema, default:()=>({}) },
  render: { type:platformStateSchema, default:()=>({}) },
  productionReady: { type:Boolean, default:false },
  error: { type:String, default:'' },
  publishedAt: { type:Date, default:null },
  completedAt: { type:Date, default:null },
}, { timestamps:true })

updateReleaseSchema.index({ createdAt:-1 })

export default mongoose.model('UpdateRelease', updateReleaseSchema)
