import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { authFetch } from '../../services/domains/http.js'
import toast from 'react-hot-toast'
const base=()=>`${import.meta.env.VITE_API_URL||'/api'}/conteudo`
export default function AdminConteudoQualidade(){
 const [data,setData]=useState(null)
 useEffect(()=>{authFetch(`${base()}/qualidade`,{credentials:'include'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.erro||'Falha');setData(d)}).catch(e=>toast.error(e.message))},[])
 return <div className="cq-page"><div className="adm-page-header"><div><div className="adm-page-title">Qualidade do conteúdo</div><div className="adm-page-sub">Pendências objetivas para corrigir sem depender de IA.</div></div></div>
 {!data?<div className="adm-card"><div className="adm-empty">Carregando…</div></div>:<div className="cq-grid">{data.grupos.map(g=><section className="adm-card cq-card" key={g.id}><div className="cq-head"><b>{g.titulo}</b><span>{g.total}</span></div>{!g.itens.length?<p className="cq-ok">✓ Nada pendente</p>:<div className="cq-list">{g.itens.map((x,i)=><div key={x._id||i} className="cq-row"><div><strong>{x.titulo||x.nome||'Item'}</strong>{x.ultimo_erro&&<small>{x.ultimo_erro}</small>}</div>{x.titulo&&<Link to={`/admin/editar/${x._id}`}>Corrigir</Link>}</div>)}</div>}</section>)}</div>}
 <style>{`.cq-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cq-card{overflow:hidden}.cq-head{display:flex;align-items:center;justify-content:space-between;padding:13px 14px;border-bottom:1px solid var(--adm-border)}.cq-head b{font-size:13px}.cq-head span{min-width:28px;height:28px;display:grid;place-items:center;border-radius:9px;background:var(--adm-surface2);font-weight:800}.cq-list{display:grid}.cq-row{display:flex;gap:10px;align-items:center;justify-content:space-between;padding:10px 14px;border-top:1px solid var(--adm-border)}.cq-row:first-child{border-top:0}.cq-row div{min-width:0;display:grid;gap:2px}.cq-row strong{font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cq-row small{font-size:10px;color:var(--adm-muted);display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.cq-row a{font-size:11px;font-weight:800;color:var(--adm-accent);text-decoration:none}.cq-ok{padding:14px;margin:0;color:#16a34a;font-size:12px}@media(max-width:680px){.cq-grid{grid-template-columns:1fr}}`}</style></div>
}
