import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { authFetch } from '../../services/domains/http.js'
import toast from 'react-hot-toast'
const base=()=>`${import.meta.env.VITE_API_URL||'/api'}/conteudo`

function Lista({titulo,itens=[],name='nome',value='views'}){return <section className="adm-card"><h3>{titulo}</h3>{!itens.length?<div className="cm-empty">Sem dados no período.</div>:itens.map((x,i)=><div className="cm-row" key={String(x._id||x.termo||i)}><span>{x[name]||'—'}</span><b>{x[value]||0}</b></div>)}</section>}
export default function AdminConteudoMetricas(){
 const [dias,setDias]=useState(30),[d,setD]=useState(null)
 useEffect(()=>{setD(null);authFetch(`${base()}/metricas?dias=${dias}`,{credentials:'include'}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.erro||'Falha');setD(x)}).catch(e=>toast.error(e.message))},[dias])
 return <div><div className="adm-page-header"><div><div className="adm-page-title">Métricas editoriais</div><div className="adm-page-sub">Leitura, origem, RSS, newsletter e buscas do portal.</div></div><select className="adm-input" style={{width:140}} value={dias} onChange={e=>setDias(Number(e.target.value))}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="365">1 ano</option></select></div>
 {!d?<div className="adm-card"><div className="adm-empty">Carregando…</div></div>:<><div className="cm-stats"><div><small>Manual</small><b>{d.origem.manual.total||0}</b><span>{d.origem.manual.views||0} views</span></div><div><small>RSS</small><b>{d.origem.rss.total||0}</b><span>{d.origem.rss.views||0} views</span></div><div><small>Sem views</small><b>{d.sem_views.length}</b><span>publicadas</span></div><div><small>Newsletter</small><b>{d.newsletter?.enviados||0}</b><span>{d.newsletter?.campanhas||0} campanha(s)</span></div></div>
 <div className="cm-grid wide"><section className="adm-card"><h3>Mais lidas</h3>{d.mais_lidas.map((n,i)=><Link key={n._id} to={`/admin/editar/${n._id}`} className="cm-row"><span>{i+1}. {n.titulo}</span><b>{n.views||0}</b></Link>)}</section><Lista titulo="Por categoria" itens={d.categorias}/><Lista titulo="Por fonte" itens={d.fontes}/><Lista titulo="Por feed RSS" itens={d.feeds}/><Lista titulo="Buscas no portal" itens={d.buscas} name="termo" value="total"/></div></>}
 <style>{`.cm-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:10px}.cm-stats>div{padding:13px;border:1px solid var(--adm-border);border-radius:12px;background:var(--adm-surface);display:grid;gap:2px}.cm-stats small,.cm-stats span{font-size:12px;color:var(--adm-muted)}.cm-stats b{font-size:22px}.cm-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cm-grid.wide section:first-child{grid-row:span 2}.cm-grid h3{font-size:13px;margin:0;padding:13px 14px;border-bottom:1px solid var(--adm-border)}.cm-row{display:flex;justify-content:space-between;gap:10px;padding:9px 14px;border-top:1px solid var(--adm-border);font-size:11px;text-decoration:none;color:var(--adm-text)}.cm-row:first-of-type{border-top:0}.cm-row span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cm-empty{padding:12px 14px;font-size:11px;color:var(--adm-muted)}@media(max-width:760px){.cm-grid{grid-template-columns:1fr}.cm-grid.wide section:first-child{grid-row:auto}.cm-stats{grid-template-columns:repeat(2,1fr)}.cm-stats>div{padding:10px}.cm-stats b{font-size:18px}}`}</style></div>
}
