import { useEffect,useMemo,useRef,useState } from 'react'
import { Link } from 'react-router-dom'
import { Copy, Loader2, RefreshCw, Trash2, Upload } from 'lucide-react'
import { authFetch } from '../../services/domains/http.js'
import { storageService } from '../../services/api'
import toast from 'react-hot-toast'

import { confirmAction } from '../../utils/confirmAction'
const base=()=>`${import.meta.env.VITE_API_URL||'/api'}/conteudo`
async function request(path,options={}){const r=await authFetch(`${base()}${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.erro||'Falha na operação');return x}

export default function AdminMidia(){
  const [d,setD]=useState({assets:[]}),[q,setQ]=useState(''),[tipo,setTipo]=useState('todos'),[loading,setLoading]=useState(true)
  const [orfaos,setOrfaos]=useState(null),[checking,setChecking]=useState(false),[uploading,setUploading]=useState(false)
  const input=useRef(null)
  async function carregar(){setLoading(true);try{setD(await request('/midia'))}catch(e){toast.error(e.message)}finally{setLoading(false)}}
  useEffect(()=>{carregar()},[])
  const assets=useMemo(()=>d.assets.filter(a=>(tipo==='todos'||a.tipo===tipo)&&(!q||`${a.titulo} ${a.alt} ${a.credito}`.toLowerCase().includes(q.toLowerCase()))),[d,q,tipo])
  async function enviar(file){if(!file)return;setUploading(true);try{const up=await storageService.uploadConteudo(file,'biblioteca');const created=await request('/midia',{method:'POST',body:JSON.stringify({...up,titulo:file.name,original_name:file.name})});toast.success('Mídia adicionada à biblioteca');await carregar();return created}catch(e){toast.error(e.message)}finally{setUploading(false);if(input.current)input.current.value=''}}
  async function verificarOrfaos(){setChecking(true);try{setOrfaos(await request('/midia/orfaos'))}catch(e){toast.error(e.message)}finally{setChecking(false)}}
  async function limparOrfaos(){if(!orfaos?.orfaos?.length)return;if(!await confirmAction(`Apagar ${orfaos.orfaos.length} arquivo(s) órfão(s) do R2?`,{title:'Limpar arquivos órfãos',confirmLabel:'Apagar'}))return;try{const x=await request('/midia/orfaos',{method:'DELETE',body:JSON.stringify({public_ids:orfaos.orfaos.map(o=>o.public_id)})});toast.success(`${x.removidos} arquivo(s) removido(s)`);await verificarOrfaos()}catch(e){toast.error(e.message)}}
  async function copiar(url){try{await navigator.clipboard.writeText(url);toast.success('URL copiada')}catch{toast.error('Não foi possível copiar')}}
  return <div>
    <div className="adm-page-header"><div><div className="adm-page-title">Biblioteca de mídia</div><div className="adm-page-sub">Mídias do Conteúdo e limpeza segura de arquivos R2 sem uso.</div></div><div className="adm-page-actions"><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>enviar(e.target.files?.[0])}/><button className="adm-btn adm-btn-secondary" onClick={verificarOrfaos} disabled={checking}>{checking?<Loader2 size={14} className="adm-spin"/>:<RefreshCw size={14}/>} Verificar órfãos</button><button className="adm-btn adm-btn-primary" onClick={()=>input.current?.click()} disabled={uploading}>{uploading?<Loader2 size={14} className="adm-spin"/>:<Upload size={14}/>} Enviar mídia</button></div></div>
    {orfaos&&<div className="adm-card orphan-box"><div><b>{orfaos.total} arquivo(s) órfão(s)</b><small>{Math.round((orfaos.total_bytes||0)/1024)} KB no R2 sem referência no Conteúdo.</small></div>{orfaos.total>0&&<button className="adm-btn adm-btn-danger adm-btn-sm" onClick={limparOrfaos}><Trash2 size={13}/> Limpar órfãos</button>}</div>}
    <div className="media-tools"><input className="adm-input" placeholder="Buscar mídia…" value={q} onChange={e=>setQ(e.target.value)}/><select className="adm-input" value={tipo} onChange={e=>setTipo(e.target.value)}><option value="todos">Todos</option><option value="midia">Biblioteca</option><option value="noticia">Notícias</option><option value="categoria">Categorias</option><option value="fonte">Fontes</option><option value="evento">Eventos</option></select></div>
    {loading?<div className="adm-card"><div className="adm-empty">Carregando mídia…</div></div>:<div className="media-grid">{assets.map(a=><article className="media-card" key={a.id}><div className="media-thumb">{a.url?<img src={a.url} alt={a.alt||''}/>:<span>Sem prévia</span>}</div><div className="media-copy"><div><b>{a.titulo}</b><small>{a.tipo} · {a.storage||'mídia'}{a.usos!=null?` · ${a.usos} uso(s)`:''}</small></div><dl><div><dt>Alt</dt><dd>{a.alt||'—'}</dd></div>{a.width&&<div><dt>Dimensões</dt><dd>{a.width}×{a.height}</dd></div>}{a.size&&<div><dt>Tamanho</dt><dd>{Math.round(a.size/1024)} KB</dd></div>}</dl><div className="media-actions"><button onClick={()=>copiar(a.url)}><Copy size={11}/> Copiar URL</button>{a.usado_em&&<Link to={a.usado_em}>Abrir uso →</Link>}</div></div></article>)}</div>}
    {!loading&&!assets.length&&<div className="adm-card"><div className="adm-empty">Nenhuma mídia encontrada.</div></div>}
    <style>{`.orphan-box{padding:10px 12px;margin-bottom:10px;display:flex;justify-content:space-between;align-items:center;gap:10px}.orphan-box b{font-size:12px;display:block}.orphan-box small{font-size:10px;color:var(--adm-muted)}.media-tools{display:grid;grid-template-columns:1fr 180px;gap:8px;margin-bottom:10px}.media-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.media-card{overflow:hidden;border:1px solid var(--adm-border);border-radius:13px;background:var(--adm-surface)}.media-thumb{aspect-ratio:16/9;background:var(--adm-surface2);display:grid;place-items:center;color:var(--adm-muted);font-size:11px}.media-thumb img{width:100%;height:100%;object-fit:cover}.media-copy{padding:10px;display:grid;gap:8px}.media-copy>b,.media-copy b{font-size:12px;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.media-copy small{font-size:10px;color:var(--adm-muted)}.media-copy dl{margin:0;display:grid;gap:4px}.media-copy dl div{display:flex;gap:7px;font-size:10px}.media-copy dt{font-weight:800;color:var(--adm-muted)}.media-copy dd{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.media-actions{display:flex;align-items:center;justify-content:space-between;gap:6px}.media-actions button,.media-actions a{border:0;background:none;padding:0;font-size:10px;font-weight:800;color:var(--adm-accent);text-decoration:none;display:inline-flex;gap:4px;align-items:center;cursor:pointer}@media(max-width:760px){.media-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:430px){.media-tools{grid-template-columns:1fr}.media-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.media-copy{padding:8px}.adm-page-actions{display:flex;overflow:auto}.orphan-box{align-items:flex-start}}`}</style>
  </div>
}
