import { useEffect, useState } from 'react'
import { Edit2, Plus, Trash2, Merge, Rss, Newspaper, Globe2, X } from 'lucide-react'
import { fontesService } from '../../services/api'
import { authFetch } from '../../services/domains/http.js'
import ImageUpload from '../../components/ImageUpload'
import ConfirmModal from '../../components/ConfirmModal'
import toast from 'react-hot-toast'

const idOf=x=>String(x?._id||x?.id||'')
const VAZIO={nome:'',url:'',dominio:'',nome_curto:'',descricao:'',credito_padrao:'',ativo:true,logo_url:'',logo_public_id:'',logo_alt:''}

function Modal({item,onClose,onSaved}){
 const novo=!item,[f,setF]=useState(item?{...VAZIO,...item}:VAZIO),[busy,setBusy]=useState(false)
 const set=(k,v)=>setF(x=>({...x,[k]:v}))
 async function salvar(e){e.preventDefault();if(!f.nome.trim())return toast.error('Nome é obrigatório.');try{setBusy(true);const payload={...f,nome:f.nome.trim(),url:f.url.trim()||null,dominio:f.dominio.trim()||null,logo_url:f.logo_url||null,logo_public_id:f.logo_public_id||null};novo?await fontesService.criar(payload):await fontesService.editar(idOf(item),payload);toast.success(novo?'Fonte criada.':'Fonte atualizada.');onSaved()}catch(e){toast.error(e.message)}finally{setBusy(false)}}
 return <div className="srcx-overlay" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><div className="srcx-modal"><div className="srcx-head"><div><b>{novo?'Nova fonte editorial':'Editar fonte editorial'}</b><small>Identidade usada por Notícias e pelos feeds RSS vinculados.</small></div><button onClick={onClose}><X size={16}/></button></div><form onSubmit={salvar}>
  <div className="srcx-grid"><div><label className="adm-label">Nome *</label><input autoFocus className="adm-input" value={f.nome} onChange={e=>set('nome',e.target.value)} placeholder="Agência Brasil"/></div><div><label className="adm-label">Nome curto</label><input className="adm-input" value={f.nome_curto||''} onChange={e=>set('nome_curto',e.target.value)} placeholder="Agência Brasil"/></div></div>
  <div className="srcx-grid"><div><label className="adm-label">Site</label><input type="url" className="adm-input" value={f.url||''} onChange={e=>set('url',e.target.value)} placeholder="https://…"/></div><div><label className="adm-label">Domínio</label><input className="adm-input" value={f.dominio||''} onChange={e=>set('dominio',e.target.value)} placeholder="Preenchido pelo site se vazio"/></div></div>
  <div><label className="adm-label">Descrição</label><textarea rows={2} className="adm-input" value={f.descricao||''} onChange={e=>set('descricao',e.target.value)} placeholder="Informação interna sobre o veículo/fonte"/></div>
  <div><label className="adm-label">Crédito padrão</label><input className="adm-input" value={f.credito_padrao||''} onChange={e=>set('credito_padrao',e.target.value)} placeholder="Ex.: Agência Brasil"/></div>
  <label className="srcx-check"><input type="checkbox" checked={Boolean(f.ativo)} onChange={e=>set('ativo',e.target.checked)}/> Fonte ativa e disponível nos formulários</label>
  <details className="srcx-detail"><summary>Logo da fonte</summary><div className="srcx-pad"><ImageUpload tipo="fontes" value={f.logo_url} publicId={f.logo_public_id} onChange={r=>setF(x=>({...x,logo_url:r?.url||'',logo_public_id:r?.public_id||'',logo_alt:x.logo_alt||`Logo ${x.nome}`}))}/><div style={{marginTop:10}}><label className="adm-label">Texto alternativo</label><input className="adm-input" value={f.logo_alt||''} onChange={e=>set('logo_alt',e.target.value)}/></div></div></details>
  <div className="srcx-actions"><button type="button" className="adm-btn adm-btn-secondary" onClick={onClose}>Cancelar</button><button className="adm-btn adm-btn-primary" disabled={busy}>{busy?'Salvando…':'Salvar'}</button></div>
 </form></div></div>
}
function MergeModal({item,items,onClose,onDone}){const[dest,setDest]=useState(''),[busy,setBusy]=useState(false);async function go(){if(!dest)return toast.error('Selecione a fonte de destino.');try{setBusy(true);const base=import.meta.env.VITE_API_URL||'/api',r=await authFetch(`${base}/conteudo/fontes/${idOf(item)}/mesclar`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({destino_id:dest})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.erro||'Falha ao mesclar');toast.success(`${d.noticias||0} notícia(s) e ${d.feeds||0} feed(s) reassociados.`);onDone()}catch(e){toast.error(e.message)}finally{setBusy(false)}}return <div className="srcx-overlay"><div className="srcx-modal srcx-small"><div className="srcx-head"><div><b>Mesclar “{item.nome}”</b><small>Notícias e feeds passam para a fonte escolhida.</small></div><button onClick={onClose}><X size={16}/></button></div><select className="adm-input" value={dest} onChange={e=>setDest(e.target.value)}><option value="">Selecione o destino…</option>{items.filter(x=>idOf(x)!==idOf(item)).map(x=><option key={idOf(x)} value={idOf(x)}>{x.nome}</option>)}</select><div className="srcx-actions"><button className="adm-btn adm-btn-secondary" onClick={onClose}>Cancelar</button><button className="adm-btn adm-btn-primary" disabled={busy} onClick={go}><Merge size={14}/> Mesclar</button></div></div></div>}

export default function AdminFontes(){const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[modal,setModal]=useState(null),[merge,setMerge]=useState(null),[del,setDel]=useState(null);async function load(){try{setLoading(true);setItems(await fontesService.listar())}catch(e){toast.error(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);async function excluir(){try{await fontesService.excluir(idOf(del));toast.success('Fonte excluída.');setDel(null);load()}catch(e){toast.error(e.message);setDel(null)}}return <><style>{`
.srcx-overlay{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.58);display:grid;place-items:center;padding:14px}.srcx-modal{width:min(650px,100%);max-height:calc(100dvh - 28px);overflow:auto;background:var(--adm-surface);border:1px solid var(--adm-border);border-radius:16px;padding:20px}.srcx-small{max-width:450px}.srcx-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:18px}.srcx-head>div{display:grid;gap:3px}.srcx-head b{font-size:16px}.srcx-head small{font-size:11px;color:var(--adm-muted)}.srcx-head button{border:0;background:none;color:var(--adm-muted);cursor:pointer}.srcx-modal form{display:grid;gap:12px}.srcx-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.srcx-check{display:flex;align-items:center;gap:7px;font-size:12px}.srcx-detail{border:1px solid var(--adm-border);border-radius:9px;overflow:hidden}.srcx-detail summary{cursor:pointer;padding:10px 12px;font-size:11px;font-weight:700}.srcx-pad{padding:0 12px 12px}.srcx-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:10px}.srcx-list{display:grid;gap:8px}.srcx-row{display:grid;grid-template-columns:auto 1fr auto;gap:11px;align-items:center;padding:11px 12px;border:1px solid var(--adm-border);border-radius:11px;background:var(--adm-surface)}.srcx-logo{width:38px;height:38px;border-radius:10px;border:1px solid var(--adm-border);background:var(--adm-surface2);display:grid;place-items:center;overflow:hidden;color:var(--adm-accent)}.srcx-logo img{width:100%;height:100%;object-fit:cover}.srcx-info{min-width:0}.srcx-title{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.srcx-title span{font-size:11px;padding:2px 6px;border-radius:999px;background:var(--adm-surface2);color:var(--adm-muted)}.srcx-info small{display:block;color:var(--adm-muted);font-size:12px;margin-top:3px}.srcx-counts{display:flex;gap:10px;font-size:12px;color:var(--adm-muted);margin-top:5px}.srcx-counts span{display:flex;align-items:center;gap:3px}.srcx-buttons{display:flex;gap:4px}@media(max-width:600px){.srcx-grid{grid-template-columns:1fr}.srcx-row{grid-template-columns:auto 1fr}.srcx-buttons{grid-column:1/-1;justify-content:flex-end;border-top:1px solid var(--adm-border);padding-top:7px}.srcx-modal{padding:15px}.srcx-actions .adm-btn{flex:1;justify-content:center}}
`}</style><ConfirmModal aberto={Boolean(del)} titulo={`Excluir “${del?.nome||''}”?`} mensagem="Se a fonte estiver em uso, use Mesclar para reassociar notícias e feeds." labelConfirmar="Excluir" onConfirmar={excluir} onCancelar={()=>setDel(null)}/>{modal!==null&&<Modal item={modal||null} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);load()}}/>}{merge&&<MergeModal item={merge} items={items} onClose={()=>setMerge(null)} onDone={()=>{setMerge(null);load()}}/>}<div className="adm-page-header"><div><div className="adm-page-title">Fontes editoriais</div><div className="adm-page-sub">Um cadastro único para notícias, créditos e feeds RSS.</div></div><div className="adm-page-actions"><button className="adm-btn adm-btn-primary" onClick={()=>setModal(false)}><Plus size={15}/> Nova fonte</button></div></div>{loading?<div className="adm-empty">Carregando…</div>:<div className="srcx-list">{items.map(f=><div className="srcx-row" key={idOf(f)}><div className="srcx-logo">{f.logo_url?<img src={f.logo_url} alt=""/>:<Globe2 size={18}/>}</div><div className="srcx-info"><div className="srcx-title"><b>{f.nome}</b>{f.ativo===false&&<span>inativa</span>}</div><small>{f.dominio||f.url||'Sem site'}{f.credito_padrao?` · crédito: ${f.credito_padrao}`:''}</small><div className="srcx-counts"><span><Newspaper size={10}/>{f.total_noticias||0} notícias</span><span><Rss size={10}/>{f.total_feeds_rss||0} feeds</span></div></div><div className="srcx-buttons"><button className="adm-btn adm-btn-ghost adm-btn-icon adm-btn-sm" onClick={()=>setModal(f)}><Edit2 size={14}/></button><button className="adm-btn adm-btn-ghost adm-btn-icon adm-btn-sm" onClick={()=>setMerge(f)}><Merge size={14}/></button><button className="adm-btn adm-btn-danger adm-btn-icon adm-btn-sm" onClick={()=>setDel(f)}><Trash2 size={14}/></button></div></div>)}{!items.length&&<div className="adm-empty">Nenhuma fonte editorial.</div>}</div>}</>}
